### ISSUE TITLE
A minor problem with insert

### ISSUE THREAD

**Issue by Quacil** [bbsimonbb/query-first#10]
Hi,

When you write 
```
insert into table
(
fieldshere
)
output inserted.Id
values
(
valueshere
)
```
 everything works fine but 
```
insert into table
(
fieldshere
)
values
(
valueshere
)
select SCOPE_IDENTITY()
``` 
generates a failing code 
```
if (result == DBNull.Value)
    return null;
 else
    return (System.Decimal)result;
```
in ExecuteScalar since return type is System.Decimal.

It's a minor issue since output inserted is preferred, but it could cause issues somewhere else. I suggest default(T) instead of null.

**Comment by bbsimonbb** [comment]
Sorry for the little  delay. This is fixed, and there's a [new vsix](https://marketplace.visualstudio.com/items?itemName=bbsimonbb.QueryFirst) on the marketplace site for download.
