### ISSUE TITLE
Nice work. But I really want to "get" the DSK ref

### ISSUE THREAD

**Issue by slathrop** [bbsimonbb/query-first#11]
I'm trying to "get" the joke about the DSK reference...

BTW, nice work. And kudos on the feature in the ASP.NET Community Standup - March 28th, 2017!

I'm also wondering about some sort of integration with Dapper and/or OrmLite... hmmm.

**Comment by bbsimonbb** [comment]
Yup. I think the DSK thing really has to go. He came outta the shower and just grabbed what he was looking for. I thought there might be a parallel. I'm not approving of the behaviour ! Having his name attached to a tool for programmers might be fitting punishment :-)

Didn't know anything about community standup. Thanks for the tip. Can I close the issue ?!

**Comment by slathrop** [comment]
Funny nonetheless. Thanks.

Sure, by all means close it out. If I have a chance to think more seriously about something to suggest for you on the Dapper or OrmLite integration I'll open a separate ticket and/or PR. :-)

**Comment by bbsimonbb** [comment]
Regarding Dapper or OrmLite, hopefully you'll have forgotten all about them once your happily using QueryFirst ;-) OrmLite is still an ORM, and still generates SQL. We are taking the opposite approach. 

QueryFirst is in a very similar space to Dapper. We take your SQL at design time and generate a C# POCO. Dapper takes your POCO and your SQL and generates (then caches) a mapping in IL, at runtime. I think my approach is better ! (I would say that.) The promise of QueryFirst is that *all errors are trapped as you type, or when you save, or, last resort, at compile time.* There should be no runtime errors from data access. With Dapper, all errors are runtime errors !

**Comment by bbsimonbb** [comment]
Bonjour Steve. Dunno if this will reach you. Did you get a chance to take QueryFirst for a spin? Is it as original as I think it is? Would it be worth a blog post?
