### ISSUE TITLE
Nulable Type

### ISSUE THREAD

**Issue by Malanin** [bbsimonbb/query-first#12]
### AdoSchemaFetcher.cs
```
case "DataType":
qf.TypeCs = SchemaTable.Rows[i].Field<System.Type>(j).FullName;
```
Sorry for my bad English. This code doesn't take into account the possibility nulable type.
And  queryFirst generate no valid code if the first field of the table is Null:
```
public virtual System.Int64 ExecuteScalar(IDbConnection conn)
{
	IDbCommand cmd = conn.CreateCommand();
	cmd.CommandText = getCommandText();
	var result = cmd.ExecuteScalar();
	if (result == DBNull.Value)
		return null;
	else
		return (System.Int64)result;
}
```
Example CREATE DATABASE statement:
```
CREATE TABLE [dbo].[Person](
        [Age] [int] NULL,
	[Id] [bigint] NOT NULL,
	[Name] [varchar](200) NULL,
	[LastName] [varchar](200) NULL,
	

)

```

**Comment by bbsimonbb** [comment]
I've just committed a fix for this. It should never have been there in  the first place, sorry. There's a [new vsix](https://marketplace.visualstudio.com/items?itemName=bbsimonbb.QueryFirst) on the marketplace site for download.
