### ISSUE TITLE
Multiqueries don't work

### ISSUE THREAD

**Issue by naasking** [bbsimonbb/query-first#15]
It's pretty easy to write multiqueries using Dapper, so any db interaction only needs to make one round trip:

    /* .sql query managed by QueryFirst add-in */

    -- designTime - put parameter declarations and design time initialization here

    -- endDesignTime

    select * from Users where UserId = @id
    select * from Projects where UserId = @id

Writing two queries in a QueryFirst .sql file like above doesn't seem to work as-is, but to truly replace Dapper this is needed.

**Comment by bbsimonbb** [comment]
I'll take this as a feature request. The GetSchemaTable method we use to retrieve the result schema ignores all resultsets after the first, so implementing this is not straightforward. 

One possible way to deal with this would be a concatenate function, letting you concatenate and send together n QueryFirst queries, each returning one result set. But each query would remain a separate entity, runnable, or at least editable, independently. With connection pooling, are you sure the performance gain is worth the complexity penalty? Are there statistics? As things stand, if you manage the connection, you can share state and local variables between successive QueryFirst queries.
