### ISSUE TITLE
SQL IN queries don't infer correct type

### ISSUE THREAD

**Issue by naasking** [bbsimonbb/query-first#16]
QueryFirst doesn't correctly infer the following:

	/* .sql query managed by QueryFirst add-in */

	-- designTime - put parameter declarations and design time initialization here

	-- endDesignTime

	select * from Users where UserId  IN(@ids)

It infers it as a simple string, but it should actually be a table-valued parameter [like this](http://stackoverflow.com/questions/7097079/c-sharp-sql-server-passing-a-list-to-a-stored-procedure) ([ADO.NET details](http://www.sommarskog.se/arrays-in-sql-2008.html#ADONET)).

**Comment by bbsimonbb** [comment]
Here again, I'll take this as a feature request. We've been talking about how best to deal with this. At present, we just transparently carry through the parameter type as reported by sp_describe_undeclared_parameters. It works, but I'm aware we could do something much better. It will be in the next version.
