### ISSUE TITLE
Generated POCO doesn't match schema

### ISSUE THREAD

**Issue by naasking** [bbsimonbb/query-first#17]
The generate POCO doesn't match the DB schema. For instance, a nullable int column generates an int field instead of a Nullable<int> field.

**Comment by bbsimonbb** [comment]
Ok that's fixed and there's a new binary on the marketplace site. Thanks for taking the time to comb through and find these. I hope, with these fixes, you'll get some use out of the thing. Would it be worth a blog post, on your blog or [mine](http://geniusorfantasist.blogspot.fr) ?

**Comment by naasking** [comment]
Without support for multiqueries and the other enhancements I suggested, I'm not sure I'd use it beyond simple prototypes. But you inspired me to add queries as embedded resources and query validation functions to [my recent project](https://github.com/naasking/Dapper.Compose), and I cited your project in as an inspiration for those features.
