### ISSUE TITLE
Non-nullable parameter inference

### ISSUE THREAD

**Issue by naasking** [bbsimonbb/query-first#18]
The following is generated by QueryFirst:

	/* .sql query managed by QueryFirst add-in */

	-- designTime - put parameter declarations and design time initialization here

	declare @id int;
	-- endDesignTime

	select * from Users where UserId = @id

Since UserId is the primary key, the parameter should really be non-null, but all of the generated C# methods accept a Nullable<int> parameter.

Depending on the complexity of the query, complete nullability inference may be infeasible, but there's a lot of low-hanging fruit like this that would enhance type safety. 

As a first-start, it seems like any query parameters compared against only non-null columns or non-null values should generate non-null parameters. Only if it's compared against a NULL value or a nullable column may the parameter be nullable.

**Comment by bbsimonbb** [comment]
For the generating declarations, QueryFirst relies entirely on sp_describe_undeclared_parameters. If this sp doesn't sniff the parameter as not nullable, we won't/can't do anything. The code generation is based on the declaration in the designTime section, so if you modify the declaration to be not null, this can/should be reflected in the generated code.
