### ISSUE TITLE
Not functioning with .net core console app

### ISSUE THREAD

**Issue by bbsimonbb** [bbsimonbb/query-first#19]
Hi,
I seem to be unable to set QueryFirst running with a aps.net core solution running on vs2017.

Can someone share a working project with QueryFirst or a detailed how to so I understand what I am missing?

For my lab I defined a console app, settle connection string and defined class "QfRuntimeConnection" with " public class QfRuntimeConnection
{
public static IDbConnection GetConnection()
{
return new SqlConnection(ConfigurationManager.ConnectionStrings["Default"].ConnectionString);
}
}"

but on output I got 
"
Object reference not set to an instance of an object. at QueryFirst.CodeGenerationContext..ctor(Document queryDoc) in C:\mydev\QueryFirstV\QueryFirst\CodeGenerationContext.cs:line 36
at QueryFirst.Conductor.ProcessOneQuery(Document queryDoc) in C:\mydev\QueryFirstV\QueryFirst\Conductor.cs:line 30
at QueryFirst.SolutionEventHandlers.myDocumentEvents_DocumentSaved(Document Document) in C:\mydev\QueryFirstV\QueryFirst\SolutionEventHandlers.cs:line 255Object reference not set to an instance of an object. at QueryFirst.QueryFirstCmd.ProcessAllItems(ProjectItems items, VSOutputWindow vsOutputWindow) in C:\mydev\QueryFirstV\QueryFirst\QueryFirstCmd.cs:line 113Object reference not set to an instance of an object. at QueryFirst.QueryFirstCmd.ProcessAllItems(ProjectItems items, VSOutputWindow vsOutputWindow) in C:\mydev\QueryFirstV\QueryFirst\QueryFirstCmd.cs:line 113Object reference not set to an instance of an object. at QueryFirst.QueryFirstCmd.ProcessAllItems(ProjectItems items, VSOutputWindow vsOutputWindow) in C:\mydev\QueryFirstV\QueryFirst\QueryFirstCmd.cs:line 113Object reference not set to an instance of an object. at QueryFirst.QueryFirstCmd.ProcessAllItems(ProjectItems items, VSOutputWindow vsOutputWindow) in C:\mydev\QueryFirstV\QueryFirst\QueryFirstCmd.cs:line 113
"
where actually there is no "mydev folder"...

thanks in advance

**Comment by Brechtvsk** [comment]
We had the same issue. You need to manually nest the gen.cs file within your sql file:
example:
```xml
ItemGroup>
    <EmbeddedResource Include="MySqlQuery.sql" />
    <Compile Update="MySqlQuery.gen.cs">
      <DependentUpon>MySqlQuery.sql</DependentUpon>
    </Compile>
    <Compile Update="MySqlQueryResults.cs">
      <DependentUpon>MySqlQuery.sql</DependentUpon>
    </Compile>
  </ItemGroup>
```

The mydev folder in the stacktrace is just the path on the computer of the developer who wrote this plugin.

It would be nice if this plugin would automatically nest the code files for .NET core projects

**Comment by AdrianBathurst** [comment]
I like the concept of this project. Please add support for .net core.

**Comment by bbsimonbb** [comment]
Hello,

I'm looking at this again now, but I'm a bit disadvantaged, with no
particular experience in .net core. What's your scenario? People developing
.net core are mostly using Visual Studio? Where does config go in .net core
apps. Should QueryFirst config go in a .net core config file, or should I
strike out on my own? So many questions!

Simon

**Comment by Quacil** [comment]
Hi Simon,

I don't know abut .net core console app but in asp.net core there is 'appsettings.json' file and a hidden 'secrets.json' file for [secrets](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-2.1&tabs=windows#secret-manager). 
In my team we use Visual Studio for Asp.net Core projects.

Lukasz

**Comment by bbsimonbb** [comment]
Ok it looks completely the wrong idea to put the design time config in
appsettings.json. This value is used only in the editor at design time, so
I think it would be best  to create our  own little config file somewhere.

I'll get onto it.

**Comment by AdrianBathurst** [comment]
I will also be using asp.net core which uses `appsettings.json`, e.g.

```
{
	"ConnectionStrings": {
		"ConnectionString": "Server=(local)\\SQLExpress;Database=xx;User Id=xx;Password=xx"
	},
	"Logging": {
		"LogLevel": {
			"Default": "Information",
			"System": "Information",
			"Microsoft": "Information"
		},
		"Console": {
			"IncludeScopes": true
		}
	}
}
```

 I did a quick test and as @Brechtvsk mentioned above, manually editing ItemGroup items in 'yourproject.csproj' will get it working.

To register the settings file, add this to `public class Program`

```
public static IWebHostBuilder CreateWebHostBuilder(string[] args)
{
    return WebHost.CreateDefaultBuilder(args)
        .ConfigureAppConfiguration((hostingContext, config) =>
        {
            config.SetBasePath(Directory.GetCurrentDirectory());
            config.AddJsonFile("appsettings.json", optional: true, reloadOnChange: true);
        })
        .UseStartup<Startup>();
}
```

Add a class to get the connection string:

```
namespace WebApp
{
    public class DbConfig
    {
        public string ConnectionString { get; set; }
    }
}
```

Add the config to services in Startup.cs:

```
public void ConfigureServices(IServiceCollection services)
{
    ...
    services.Configure<DbConfig>(_config.GetSection("ConnectionStrings"));
}
```

Access the connection string through dependency injection:

```
public class XXX
{
        DbConfig _dbConfig { get; }

        public XXX(IOptions<DbConfig> dbConfig)
        {
            _dbConfig = dbConfig.Value;
        }

        private void YYY()
        {
            string connString = _dbConfig.ConnectionString;
        }
}
```

**Comment by AdrianBathurst** [comment]
ah, of course...this doesn't work in your case for design time!

**Comment by AdrianBathurst** [comment]
Thanks, I'll give it a try.

First issue I've come across, in a .net core `web app`, I don't get the option to select a new QueryFirst Query template, but in .net core `console app` I do....

![2018-10-17_175716](https://user-images.githubusercontent.com/9006517/47103307-e3664f00-d236-11e8-967f-82f13760ac4b.png)


![2018-10-17_175647](https://user-images.githubusercontent.com/9006517/47103312-e82b0300-d236-11e8-81ae-92fce8ea65b1.png)

**Comment by Quacil** [comment]
The nesting issue can be solved in net core Web app using custom [nesting rules](https://blogs.msdn.microsoft.com/webdev/2018/02/07/file-nesting-in-solution-explorer/). But unfortunately there is no such option for net core console nor net core library projects.

**Comment by AdrianBathurst** [comment]
Using the 'core' version of the extension, though I typically use web apps, I've done a test using a new .net core console app, I get this error when saving a query...

```
Registering types...
Registered types...
Object reference not set to an instance of an object.   at QueryFirst.CodeGenerationContext..ctor(Document queryDoc) in C:\mydev\QueryFirstV\QueryFirst\CodeGenerationContext.cs:line 39
   at QueryFirst.Conductor.ProcessOneQuery(Document queryDoc) in C:\mydev\QueryFirstV\QueryFirst\Conductor.cs:line 30
   at QueryFirst.SolutionEventHandlers.myDocumentEvents_DocumentSaved(Document Document) in C:\mydev\QueryFirstV\QueryFirst\SolutionEventHandlers.cs:line 255
```

I have `qfconfig.json` at the root of the project.

**Comment by AdrianBathurst** [comment]
Manually editing the project.csproj file...

Before:
```
<ItemGroup>
  <None Remove="MyQuery.sql" />
</ItemGroup>

<ItemGroup>
  <EmbeddedResource Include="MyQuery.sql" />
</ItemGroup>
```

After:
```
<ItemGroup>
    <EmbeddedResource Include="MyQuery.sql" />
    <Compile Update="MyQuery.gen.cs">
      <DependentUpon>MyQuery.sql</DependentUpon>
    </Compile>
    <Compile Update="MyQueryResults.cs">
      <DependentUpon>MyQuery.sql</DependentUpon>
    </Compile>
</ItemGroup>
```

Then it generates the code files successfully.

**Comment by bbsimonbb** [comment]
Nesting is still broken, but the template should appear for all C# projects, as of v1.0.0. QueryFirst should now be compatible .net core.
