### ISSUE TITLE
Options to exclude generation of resulting classes and allow access to SQL string

### ISSUE THREAD

**Issue by TGMarkPalnau** [bbsimonbb/query-first#21]
I was curious, without doing too much investigation into the code, if there is currently a way to access the parsed SQL string resulting from the SQL file, and an option to not generate the resulting POCO.

Reason being, we are currently using dapper in our repositories to execute our SQL in-line. To avoid rework, and to make use of dapper's dynamic parameters for stored procedures, we could use the SQL resource as a string reference for dapper's query call.

Additionally, we make use of multiple result sets from certain queries which looks like it may not currently be supported (of course, they could be split into two separate query files instead, unless it is a stored procedure).

However, if it is a better idea, we could refactor the calls to use QueryFirst instead of dapper if we do not lose any functionality that we are using. Most likely QueryFirst would cover our mostly basic use-cases though.

Thoughts?

**Comment by bbsimonbb** [comment]
Keeping your SQL in a .sql file is a _very good idea_, (and not my idea). If this is all you want, just right click on the file in your solution explorer and choose properties => build action => Embedded resource. Then `Assembly.GetManifestResourceStream()` to access it. If your sql goes over 1 line, I think this is worth the hassle. You can also use our trick of keeping test data as local variables in a comments section that you open when editing and close when compiling.

With connection pooling, I'm yet to be convinced that supporting multiple result sets is a priority. When is it not better to break a multiple-result-set statement into it's components? You can pass around the connection between QueryFirst queries so they have access to the same state and local variables on the DB.

QueryFirst will appeal to the same folk as Dapper, but does things quite differently. So for me there's not really a question of making them work together. Dapper is much more mature and has different strengths. If you start using QueryFirst for the things for which you find it suited, we'll work progressively at removing obstacles and enlarging the perimeter.

**Comment by TGMarkPalnau** [comment]
I think I'm in agreement with everything said, but just to be sure I wanted to clarify what I meant by the access to the SQL.

In the generated file, there is this method:
`private string getCommandText()`

It does what you are saying, but generates the method to call the particular SQL file we are working with. If this method was optionally made public:
`public string getCommandText()`

We could make a dapper call by accessing the resource, with the correct file generated from QF:
```
    using (var multiple = conn.QueryMultiple(new DAL.Sql.QueryTest().getCommandText(), new { Id = Id }))
    {
```
etc.

And yeah we should be able to access the same temporary tables until the connection is broken or is managed ourselves. Depending on complexity though, it could become more difficult to manage when spread across multiple SQL files... I also doubt it would be able to generate a selection from temporary tables... The multiple result set that we are using is creating a temporary table to map the first part of the query then is combined with the second result set, making it more efficient than querying multiple times for the same data, and avoids passing the results of the first set to the second.

Again, I really like the tool, I'm just afraid that the whole team may not be on-board with this approach as it is. A suggestion was to do what you mentioned, to use the resource stream to access it.

I proposed that we could fork the repo and make the query string resulting from the generated resource, because it generates the filename that we want to access. Of course we can write our own method that passes the name of the file to access the resource as well, if this breaks the concept/idea behind this tool 😅

**Comment by bbsimonbb** [comment]
If making one method public gets you out of a hole, then no problem. We'll leave the issue open, and I'll fix it for you. You still get some benefits from having all your queries continually tested, even if you bypass the generated code at runtime.

**Comment by TGMarkPalnau** [comment]
Fantastic! This way I can use QF's generated calls for the most part, but won't be stuck when we are handed a multiple-result query or otherwise. Plus, we reuse models when different queries give the same resulting model, so we may be casting results or executing the query string with an auto-mapper anyway.

Of course we have automated unit testing in place to test all models, queries, and endpoints too, so it will catch if there are any problems with any call either way it is handled.

**Comment by TGMarkPalnau** [comment]
PR accepted for changing private method to public.
