### ISSUE TITLE
Ideas For Furthering This Project

### ISSUE THREAD

**Issue by jon49** [bbsimonbb/query-first#27]
I love what you have done with this and would love to see it work with .NET Core. I had some more ideas what what could be done and am implementing them in my own library. I'm not sure I would know how to extract your project from VS to get it to work. I'm not sure if I'm quite as good of a coder as you either. But here is something that I've started working on with the readme saying all the ideas that I have for making the SQL code generation a step further.

Let me know what you think! Also, I would like to know how this has worked out for you. Are you using it at your day job? Having you run into any snares? SQL is a great language and it seems like we could get a lot more done by not having to write all this cruft code!

https://github.com/jon49/SQLClient

**Comment by bbsimonbb** [comment]
I couldn't agree more ! So, no, I haven't yet convinced my employer, which means I'm going up the wall debugging sql constructed with string methods at runtime. I would love to get it working for .NET Core. I'll keep an eye on your efforts.

**Comment by jon49** [comment]
Yeah, I haven't kept working on it. My employer doesn't seem to want to go in that direction either. They like to keep the queries overly simple. So, I'm working on a different way to make it declarative at least for each different view of the data.

Good to hear you still like it!
