### ISSUE TITLE
query.gen.cs empty 

### ISSUE THREAD

**Issue by rcoxon** [bbsimonbb/query-first#28]
Installed the vsix, created the QfDefaultConnection and QfRuntimeConnection in the settings, created the QfRuntimeConnection.GetConnection method to return a SqlConnection from the QfRuntimeConnection setting. 

Created a new .sql from the template, attached to a database, created and tested a query, but on save (and Build/ReBuild) nothing gets generated in the query.gen.cs class, and I get object reference errors in the Output|QueryFirst window: 

Object reference not set to an instance of an object.   at QueryFirst.CodeGenerationContext..ctor(Document queryDoc) in C:\mydev\QueryFirstV\QueryFirst\CodeGenerationContext.cs:line 36
   at QueryFirst.Conductor.ProcessOneQuery(Document queryDoc) in C:\mydev\QueryFirstV\QueryFirst\Conductor.cs:line 30
   at QueryFirst.SolutionEventHandlers.myDocumentEvents_DocumentSaved(Document Document) in C:\mydev\QueryFirstV\QueryFirst\SolutionEventHandlers.cs:line 255

Any help appreciated (looked through StackOverflow and the GitHub issues). 

Thanks!

**Comment by bbsimonbb** [comment]
sounds like you need a provider name on your connection string. Sql Server? try providerName="System.Data.SqlClient"

**Comment by bbsimonbb** [comment]
Sorry about the cryptic error message.

**Comment by rcoxon** [comment]
Thanks for the response!

I do have the provider name in the connection string, and have tried both trusted connection and direct with an sa account:
```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6.2" />
    </startup>
  <connectionstrings>
    <add name="QfDefaultConnection" connectionstring="Server=EM-BK-DEV-DATA;Integrated Security=False;Database=EmpireBPM;ID=sa;Password=*********;TrustServerCertificate=True;" providername="System.Data.SqlClient"/>
  </connectionstrings>
  <connectionstrings>
    <add name="QfRuntimeConnection" connectionstring="Server=EM-BK-DEV-DATA;Integrated Security=False;Database=EmpireBPM;ID=sa;Password=**********;TrustServerCertificate=True;" providername="System.Data.SqlClient"/>
  </connectionstrings>
</configuration>
```

Still getting an error, thought I have gotten slightly farther (it was not clear to me whether to create the method _QfRuntimeConnection.GetConnection()_ or _QfRuntimeConnection.GetConnectionString()_, and I have tried either, and both, with no joy):
```
Object reference not set to an instance of an object.   at QueryFirst.CodeGenerationContext..ctor(Document queryDoc) in C:\mydev\QueryFirstV\QueryFirst\CodeGenerationContext.cs:line 36
   at QueryFirst.Conductor.ProcessOneQuery(Document queryDoc) in C:\mydev\QueryFirstV\QueryFirst\Conductor.cs:line 30
   at QueryFirst.QueryFirstCmd.ProcessAllItems(ProjectItems items, VSOutputWindow vsOutputWindow) in C:\mydev\QueryFirstV\QueryFirst\QueryFirstCmd.cs:line 120
```

**Comment by rcoxon** [comment]
Accidentally closed the issue  :(

**Comment by bbsimonbb** [comment]
Starting today, for .net core compatibility, QueryFirst no longer looks in app or web.config. See the readme for up-to-date details. You need to put these parameters in a qfconfig.json, beside or anywhere above the .sql file.

**Comment by AdrianBathurst** [comment]
Question about the qfconfig.json file, what is this: `"helperAssembly":[pathToDll],` - what path (relative or absolute) to what dll? An example please, thanks!

**Comment by dialedin2014** [comment]
I am having this same problem.  Was it ever resolved?

**Comment by efurban** [comment]
had the same issue and just got it working by adding the QfRuntimeConnection.cs file with the following: 
```
{
  "defaultConnection": "yourconnectionstring",
  "provider": "System.Data.SqlClient" ,
  "makeSelfTest": false
}

```
* removed the helper dll line.

**Comment by bbsimonbb** [comment]
You don't need to worry about these options to get started. Leave out helperAssembly completely, and we won't look for one. Leave out selfTest and it defaults to false. defaultConnection and provider are absolutely necessary, otherwise we don't know what db to run your query against.
