### ISSUE TITLE
Unable to mention optional parameter to the query

### ISSUE THREAD

**Issue by vijaysg** [bbsimonbb/query-first#3]
My SQL Code:
```
---SelectUser.SQL
---designTime ...
DECLARE @PageSize INT = 50;
DECLARE @CurrentPage INT = 50;
DECLARE @UserId INT = NULL;
---endDesignTime

SELECT Col1,Col2 FROM MyTable WHERE (@UserId IS NULL OR Col3=@UserId) 
ORDER BY ... 
```

When trying to run the above query:
```
var db = new SelectUser();
var userList = db.Execute(50,1,null);
```
I am getting an exception saying that it is expecting the parameter `@UserId` even though I want to pass NULL and I am doing so from the code.

Any pointers would be appreciated.

**Comment by bbsimonbb** [comment]
Message received. I'll have a look at this this evening.

**Comment by bbsimonbb** [comment]
This should be fixed. If the parameter value is null, DBNull.Value will be assigned, so your query should be able to test null as expected. This change is also on the [VS gallery](https://visualstudiogallery.msdn.microsoft.com/eaf390af-afc1-4994-a442-ec95923dafcb) site if you want to download from their.

**Comment by vijaysg** [comment]
Thank you Simon.

Small observation though, shouldn't the visual studio gallery version now read 0.4 instead of 0.2?
