### ISSUE TITLE
Multiple connections strings

### ISSUE THREAD

**Issue by john-rossell-gpan** [bbsimonbb/query-first#30]
Hi, is it possible to work with multiple connection strings in a single project?
If appears only single connection via QfDefaultConnection is supported.

**Comment by bbsimonbb** [comment]
Yup. You can specify the design time connection string directly in the .sql. Put --QfDefaultConnection=[myConnectionString] somewhere in your SQL. When the query is executed in the code, your QfRuntimeConnection class will be called, so you can put in whatever logic you like. Does that meet the requirement ?
