### ISSUE TITLE
*.sql files Dont have to be EmbeddedResource

### ISSUE THREAD

**Issue by Quacil** [bbsimonbb/query-first#34]
Hello,

Since the whole query text is inside *.gen.cs files now, *.sql files don't have to have build action "EmbeddedResource" anymore.

**Comment by bbsimonbb** [comment]
Does the issue relate to new queries ones created with the previous version? For new queries, the build action should already be 'do not copy' ?

**Comment by bbsimonbb** [comment]
Absolutely. Well spotted. I'll get onto it.

**Comment by bbsimonbb** [comment]
Sorry, I'm getting my wires crossed. Today, the build action is "None" and the Copy to output is "Do not copy" on the file in the template project, but I see this changes at some point. I'll look into it...

**Comment by bbsimonbb** [comment]
Thanks for your interest !
