### ISSUE TITLE
type not matched : uniqueidentifier

### ISSUE THREAD

**Issue by siewers** [bbsimonbb/query-first#4]
Hi

I'm just trying out the extension, but it's not working since the uniqueidentifier type isn't matched.

I'd love to try it out, but unfortunately it's impossible :(

**Comment by bbsimonbb** [comment]
Just seeing this now. I'll get right onto it.

**Comment by bbsimonbb** [comment]
Ok this is fixed in version 0.4. New binaries on the gallery site. Thanks for bringing this to my attention.

**Comment by bbsimonbb** [comment]
Did this fix your problem? Have you had a chance to verify?
