### ISSUE TITLE
Putting sql files in project sub folders in .net core creates exception 'Object reference not set to an instance of an object.'

### ISSUE THREAD

**Issue by SailorTurkey** [bbsimonbb/query-first#41]
Hello,
When i create an sql file in project root folder, it works as expected,
but when i try to create the same sql file (with same sql) under a subfolder as seen in the picture below, i get an 'object reference' exception,

Please advise :)

![image](https://user-images.githubusercontent.com/32933607/51079481-bbbd4080-16d8-11e9-8c3c-7b8ac393191a.png)

Console:

QueryFirst generated wrapper class for Query1.sql

Object reference not set to an instance of an object.   at QueryFirst.CodeGenerationContext.InitForQuery(Document queryDoc) in D:\git\QueryFirst\QueryFirst\CodeGenerationContext.cs:line 55
   at QueryFirst.Conductor.ProcessOneQuery(Document queryDoc) in D:\git\QueryFirst\QueryFirst\Conductor.cs:line 31
   at QueryFirst.SolutionEventHandlers.myDocumentEvents_DocumentSaved(Document Document) in D:\git\QueryFirst\QueryFirst\SolutionEventHandlers.cs:line 143

**Comment by bbsimonbb** [comment]
Fixed with 208595e
