### ISSUE TITLE
TVF Support

### ISSUE THREAD

**Issue by SailorTurkey** [bbsimonbb/query-first#43]
QueryFirst doesn't support TVF Tables, always creates empty 'Results' class, half-generated .gen.cs class.

Sample TVF (MSSQL):

```
CREATE FUNCTION [dbo].[TVLTest]()
RETURNS @X TABLE
(
A INT PRIMARY KEY,
B VARCHAR(20)
)
AS
BEGIN
INSERT INTO @X 
SELECT 01 Code, 'Ticket' Description
RETURN;
END
```

![image](https://user-images.githubusercontent.com/32933607/51220220-6174e780-1945-11e9-8a1f-544a755b9678.png)

**Comment by bbsimonbb** [comment]
This is fixed but not extensively tested. You've had to wait a while but I'd be very interested to hear your feedback. The new version will be on the marketplace site in a day or two, or you can compile directly from github.
