### ISSUE TITLE
DateTime is not nullable

### ISSUE THREAD

**Issue by MarkLTX** [bbsimonbb/query-first#44]
I just got version 1.02 of QueryFirst via the Visual Studio "Extensions and Updates" feature.  I'm using VS 2017.  I have a table with a nullable datetime2(7) column but the corresponding property in the generated POCO class is not nullable.  The ints and bools are nullable but not the DateTime.

**Comment by bbsimonbb** [comment]
I'll fix that right away...

**Comment by AdrianBathurst** [comment]
Couldn't replicate issue, I get a nullable type for datetime2. Could you provide steps to replicate please?

**Comment by bbsimonbb** [comment]
Yup this is working perfectly for me. Closing
