### ISSUE TITLE
Visual Studio 2019 compatibility

### ISSUE THREAD

**Issue by AdrianBathurst** [bbsimonbb/query-first#49]
Appears this is not compatible with Visual Studio 2019. Possibly because it needs this update...

https://github.com/Microsoft/VSSDK-Extensibility-Samples/tree/master/AsyncPackageMigration

**Comment by AdrianBathurst** [comment]
@bbsimonbb are you able to look into getting this compatible with VS2019 please?

**Comment by bbsimonbb** [comment]
Yes. Thanks for the link. I'll get onto it.

**Comment by AdrianBathurst** [comment]
Thanks!

This is not my area of expertise, so not entirely sure if it's correct, but I had a go at modifying the async package and it seemed to work, well, the "_not be compatible with future versions_" message disappeared. 
I could test the solution in VS2019 and everything worked fine. Just when it came to trying to install the built .vsix, it didn't detect the VS2019 instance to install to. It installed ok into the VS 2017 instance.

Here's what I did, please give it a try and change as necessary...

- Upgraded all projects to target `.NET Framework v4.7.2`
- Installed nuget package `Microsoft.VisualStudio.Shell.15.0`.
- There were a couple of reference conflicts with older referenced versions, I just removed the reference of those that caused the conflict.

In `QueryFirstCmdPackage.cs`

changed these two declarations to:
```
[ProvideAutoLoad(UIContextGuids80.SolutionExists, PackageAutoLoadFlags.BackgroundLoad)]
[PackageRegistration(UseManagedResourcesOnly = true, AllowsBackgroundLoading = true)]
```

changed this to be an async package:
```
public sealed class QueryFirstCmdPackage : AsyncPackage, IVsShellPropertyEvents
```

changed the Initialize method to the async equivalent:
```
protected override async System.Threading.Tasks.Task InitializeAsync(CancellationToken cancellationToken, IProgress<ServiceProgressData> progress)
{
    await this.JoinableTaskFactory.SwitchToMainThreadAsync(cancellationToken);  // added

    QueryFirstCmd.Initialize(this);
    await base.InitializeAsync(cancellationToken, progress);  // changed to async

    // sby : set an eventlistener for shell property changes
    IVsShell shellService = await GetServiceAsync(typeof(SVsShell)) as IVsShell;  // changed to async
    if (shellService != null)
        ErrorHandler.ThrowOnFailure(shellService.AdviseShellPropertyChanges(this, out cookie));
    // do it anyway
    zombieProofInitialization();
}
```

**Comment by AdrianBathurst** [comment]
I also used this extension: `Microsoft.VisualStudio.SDK.Analyzers`

It's "_A collection of analyzers to help Visual Studio extension developers write quality code._"

**Comment by AdrianBathurst** [comment]
Spoke too soon about it working fine in VS2017...when .vsix is installed & I run a solution, it complains that it can't find the Microsoft.VisualStudio.Shell.15.0.dll. I haven't tried to solve that yet.

@bbsimonbb Here's another link that may help with migration...

https://devblogs.microsoft.com/visualstudio/how-to-upgrade-extensions-to-support-visual-studio-2019/

**Comment by dialedin2014** [comment]
I got a popup message in Visual Studio 2017 today to upgrade.  2019 is becoming more mainstream.

**Comment by MarkLTX** [comment]
Half of my team is on VS 2019 and cannot use QF.  I'm becoming concerned it might be abandonware.

**Comment by AdrianBathurst** [comment]
I managed to get it working on VS2019, I'll do a PR soon. Bit of patience as I'm busy at the mo, but will do it.

**Comment by AdrianBathurst** [comment]
@bbsimonbb  Pull request made.

**Comment by bbsimonbb** [comment]
Pull request merged thanks Adrian. @AdrianBathurst That's by far the biggest contribution I've accepted on this project. I'm very happy that you saw fit to do this. Thanks very much. @MarkLTX are you currently using or evaluating ?

**Comment by bbsimonbb** [comment]
Updated build is live in the store.

**Comment by dialedin2014** [comment]
Excellent!  Thanks, guys :)
