### ISSUE TITLE
IQueryable support

### ISSUE THREAD

**Issue by hidegh** [bbsimonbb/query-first#5]
Is there any way to have iqueryable support that alters the original view (query)? Any plans for it?

**Comment by bbsimonbb** [comment]
This seams to be a mile away from what I'm trying to do. Can you tell me more about how you see this working?

**Comment by hidegh** [comment]
I haven't said it'll be easy. Actually you already got a SQL, due to POCO and mapping you do you already have everything you need to decorate the SQL (apply query or wrap original into a new select to...); Anything to add parameters or extend original view with query in a typesafe way;

What i'd like to know if there are some perf. measures against EF with change detection and against EF with change detection turned off (or benchmark against dapper). For example according the article below EF with change tracking turned off has only 10% perf. penalty over Dapper: http://weblogs.asp.net/fbouma/fetch-performance-of-various-net-orm-data-access-frameworks-part-2

I'd advise you to check out https://fluentado.codeplex.com/. Getting clear ADO.NET commands towards **type safety** and mixing it with the concept you've started it could result in a very cool project. I can imagine it using on some real perf. projects somewhere around HW, data collecting and so.

**Comment by bbsimonbb** [comment]
Regarding performance, I haven't done benchmarks specifically on QueryFirst, but the output of my code generation is absolute vanilla ADO, so performance will be ADO performance. Thanks for the link to fluentado. I'm militant about developer comfort, so very interested in fluent. There's still all that SQL in string literals though. Yuck. I'll close this issue, and bear your suggestions in mind.

**Comment by hidegh** [comment]
hi, i've found something you might be interrested in:
https://github.com/linq2db/linq2db/wiki/Introduction...
