### ISSUE TITLE
Won't install on VS 2013 Pro

### ISSUE THREAD

**Issue by mapomatic** [bbsimonbb/query-first#50]
Hey, this looks like it would be an incredibly useful tool, but I ran into this when attempting to install on VS 2013 Pro.
![image](https://user-images.githubusercontent.com/19505091/57172446-1c8a9900-6dee-11e9-96d4-6621d4815dd0.png)

[VSIXInstaller_b5338df0-615b-40dc-810e-e20a33faf443.log](https://github.com/bbsimonbb/query-first/files/3143940/VSIXInstaller_b5338df0-615b-40dc-810e-e20a33faf443.log)

Let me know if I'm missing something else that's required, or if you need more details.  Thanks!

**Comment by bbsimonbb** [comment]
I'm not sure how I'm going to tackle this. VS 2013 is getting to be quite old. The first versions supported VS 2013 but I don't think I have this installed any more for testing. Would you like to paste the contents of the install log into the issue please ?

**Comment by mapomatic** [comment]
Thanks for getting back to me!  I'll take a look when I get a chance.  I understand if you can't / won't update to accommodate VS 2013.  It's what I'm stuck with for now at work, but I imagine most serious developers have moved on and it might not be a good use of your time if it's not a simple / quick fix.

**Comment by bbsimonbb** [comment]
This problem and the fix is described [here](https://docs.microsoft.com/en-us/archive/msdn-magazine/2017/august/visual-studio-creating-extensions-for-multiple-visual-studio-versions). Since it's complicated and not very elegant, this is a won't fix. I'm going to close this for now.
