### ISSUE TITLE
empty .gen.cs andResults.cs files

### ISSUE THREAD

**Issue by efurban** [bbsimonbb/query-first#54]
Hi, 
Great project but I am having a hard time getting it working. 

after adding the sql (Query1.sql), the .gen.cs file shows: 
`/* Generated code goes here. Don't bother modifying this file */`

and the result file: 
```
using System;

namespace TradeTicket.DAL
{
    [Serializable]
    public partial class Query1Results
    {
        // Partial class extends the generated results class
        // Serializable by default, but you can change this here		
        // Put your methods here :-)
        internal void OnLoad()
        {
        }
    }
}

```

Is there anything else I need to do?  (I do have the QfRuntimeConnection.cs in place) 
Thanks.

**Comment by efurban** [comment]
got it working by adding the QfRuntimeConnection.cs file with the following:
```

{
  "defaultConnection": "yourconnectionstring",
  "provider": "System.Data.SqlClient" ,
  "makeSelfTest": false
}
```

removed the helper dll line.

**Comment by bbsimonbb** [comment]
Ok looks like you're up and running.
