### ISSUE TITLE
stored procedure sp_describe_undeclared_parameters

### ISSUE THREAD

**Issue by GuillaumeDumo** [bbsimonbb/query-first#6]
La fonction DiscoverParams() appelle la procédure stocker "sp_describe_undeclared_parameters" qui n'est déclaré a aucun moment.

**Comment by GuillaumeDumo** [comment]
SQL Server 2012 minimum

**Comment by bbsimonbb** [comment]
Maintenant, ça échoue silencieusement si la procédure stockée n'est pas présent.
