### ISSUE TITLE
VS 2019 crashes adding QF query

### ISSUE THREAD

**Issue by dialedin2014** [bbsimonbb/query-first#64]
The Visual Studio Solution Explorer Add New dialog completes successfully using the QF template.  I see the SQL file added to the project.  It has a triangle next to it indicating sub-items.  I wait 5 seconds, and VS shuts down.  Upon re-opening VS, the new SQL file is missing.  Looking in Window Explorer, the SQL files and the cs sub-items exist in the folder.  They are just not included in the project.  After manually adding them to the project, the cs files are not sub-items of the SQL file.

**Comment by LKuzma** [comment]
I have the same issue. I am using VS 16.6.2 with QueryFirst 1.1.4.
Is there any one who has previous version of QueryFirst ?

**Comment by bbsimonbb** [comment]
Hi. I will look at this right away. I've added a feature to connect the editor window to the DB when you open a query. It's great when it works, but I've seen this hang VS sometimes, so I've hidden it behind a flag in qfconfig.json, connectEditor2DB. You could help me narrow this down by telling me have you got the flag set? By default it's false and no value is treated as false. Also, You've said creating a new query kills it. What about opening an existing one? Thanks for your understanding while we get this fixed.

**Comment by LKuzma** [comment]
Its happens when i create new query and when i open existing one.
If query was open before VS starts, nothing is happen.

**Comment by bbsimonbb** [comment]
I'm sorry but I'm not able to reproduce. I have VS Community 16.6.2, QueryFirst 1.1.4. I've tried all variants of connectEditor2DB: true, false and no value. Creating a query, opening an existing query etc. all work fine for me. 

Can you please run[ VS with the /Log switch](https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-use-the-activity-log?view=vs-2019), then look in ActivityLog.xml to see if there is any trace of the problem. 

Thanks for your help with this.

**Comment by bbsimonbb** [comment]
Christopher part of the behaviour you see is normal. The nesting of files is the QueryFirst wizard modifying the .csproj. If VS crashes before the .csproj is saved, then the nesting will be lost. The problem is why did VS crash in the first place.

**Comment by LKuzma** [comment]
@bbsimonbb
I opened existing query file, that should be included in the log file [MyActivityLog](https://www.dropbox.com/s/d0kxgf53mpztxfo/ActivityLog.xml?dl=0), could you take a look, is there something not right ? Query file opens and ofter 5 sec VS reboots.

**Comment by bbsimonbb** [comment]
Absolutely nothing remarkable in the logs, but thanks for taking the time. I don't know where to go with this now. If you're keen, you could clone the project from github, open it and press play, you should see the experimental instance of VS. If you can reproduce the issue in there we should see something.

**Comment by LKuzma** [comment]
I found cause of reboots of VS. Looks like DataContractJsonSerializer dont allow to use comments in json file. I was looking for equivalent of
`var options = new JsonSerializerOptions
{
    ReadCommentHandling = JsonCommentHandling.Skip,
    AllowTrailingCommas = true,
};`
that i know from `System.Text.Json` but i did not find.

Here are screen shots of this errors: [existingQuery](https://www.dropbox.com/s/oc0ckwrk6ced8jx/existingQuery.png?dl=0), [newQuery](https://www.dropbox.com/s/ogw4l13tqbtq72u/newQuery.png?dl=0).
So i got rid of comments from `qfconfig.json` file and it worked.

I think that your extension is superb and i am happy that i can use it now. Maybe sometime in the future comments in gfconfig.json file will be allowed.

**Comment by dialedin2014** [comment]
I love this extension too :)

I have some time to play around with it later today and will look for comments in qfconfig.

**Comment by bbsimonbb** [comment]
That's great. Thanks for tracking this down. I'll put in the fix right away, at least to stop the editor from crashing! If you're feeling bold, put "connectEditor2DB" : true in your qfconfig.json and enjoy having your query windows automagically connecting to the DB. Then please don't hesitate to [leave a review](https://marketplace.visualstudio.com/items?itemName=bbsimonbb.QueryFirst&ssr=false#review-details). They really help to get the word out. Chris I can see you've already done so, thanks.
