### ISSUE TITLE
No query parameters generated

### ISSUE THREAD

**Issue by Quacil** [bbsimonbb/query-first#7]
Hi,
I have noticed a problem with backward compatibility. If you have --designTime instead of -- designTime
and --endDesignTime instead of -- endDesignTime, the extension generates class with no query parameters.
sql:
```
--designTime - put parameter declarations and design time initialization here


declare @id int;
--endDesignTime
select * from Items where Id = @id;

```
generates:
 ```
public interface IGetItemsById
    {

        List<GetItemsByIdResults> Execute();
        IEnumerable<GetItemsByIdResults> Execute(IDbConnection conn);
        GetItemsByIdResults GetOne();
        GetItemsByIdResults GetOne(IDbConnection conn);
        System.Int32 ExecuteScalar();
        System.Int32 ExecuteScalar(IDbConnection conn);
        GetItemsByIdResults Create(IDataRecord record);
        int ExecuteNonQuery();
        int ExecuteNonQuery(IDbConnection conn);
    }
...
```
Best regards.

**Comment by bbsimonbb** [comment]
Hi. Thanks for your eagle eyes. This should be fixed. Could you try uninstalling and reinstalling. As you've spotted, the comments tags now have a space after the dashes, necessary to be legal MySql comments. The tool should convert all comments to the new syntax whenever you open or save a query, or in batch when you choose "someone changed my schema". Workaround - add the spaces by hand. I'll test this again when I get home.
