### ISSUE TITLE
A couple update possibilities

### ISSUE THREAD

**Issue by me-slove** [bbsimonbb/query-first#8]
Hey Simon,

Nice work here.  Since it looks like I caught you in the middle of an update cycle I am just going to create an issue and let you decide how to handle the changes (ignoring them is perfectly valid as I don't know your thoughts for the direction of the project).

We are starting to use it to help with regression testing across databases.  That leads to a couple of issues.

First, the run-time connection does not have a way to know what the command text was.  I could have used the connection parameter version but it seemed clunky.  I updated WrapperClassMaker at about line 42,77, and 108.

            code.AppendLine("using (IDbConnection conn = QfRuntimeConnection.GetConnection(getCommandText()))");

Second, it looks like there was a bug in the regex (using $ didn't provide a match) for picking up the QfDefaultConnection at design time.  I updated DesignTimeConnectionString at about line 30 and following with an allowance to pick an existing connection string from the app.config or specify a connection string.

                    var match = Regex.Match(_ctx.Query.Text, "--QfDefaultConnection(=|:)(?<cstr>.*)");
//                    var match = Regex.Match(_ctx.Query.Text, "--QfDefaultConnection(=|:)(?<cstr>.*)$");
                    //var match = Regex.Match(Query.Text, "--QfDefaultConnectionString ?(=|:)? ?\"?(?<cstr>[^ \"]*)\" ? $");
                    if (match.Success)
                    {
                        var cstr = match.Groups["cstr"].Value;
                        if (cstr.EndsWith("\r"))
                        {
                            cstr = cstr.Remove(cstr.Length - 1);
                        }
                        string providerName;
                        var matchProviderName = Regex.Match(_ctx.Query.Text, "--QfDefaultConnectionProviderName(=|:)(?<pn>.*)$");
                        if (matchProviderName.Success)
                        {
                            providerName = matchProviderName.Groups["pn"].Value;
                            _v = new ConnectionStringSettings("QfDefaultConnection", cstr, matchProviderName.Groups["pn"].Value);
                        }
                        else
                        {
                            if (_ctx.ProjectConfig.ConnectionStrings[cstr] != null)
                            {
                                _v = _ctx.ProjectConfig.ConnectionStrings[cstr];
                            }
                            else
                            {
                                _v = new ConnectionStringSettings("QfDefaultConnection", cstr, "System.Data.SqlClient");
                            }
                            //                            _v = new ConnectionStringSettings("QfDefaultConnection", cstr, "System.Data.SqlClient");
                        }

Third,  making the change to allow for different connections, here is the way I put together the QfRuntimeConnection class as a user.  This is only the Sql Server version but each user would have to deal with it separately.

        public static IDbConnection GetConnection(string cmdText)
        {
            var match = Regex.Match(cmdText, "--QfDefaultConnection(=|:)(?<cstr>.*)");
            if (match.Success)
            {
                var cstr = match.Groups["cstr"].Value;
                if (cstr.EndsWith("\r"))
                {
                    cstr = cstr.Remove(cstr.Length - 1);
                }

                if (ConfigurationManager.ConnectionStrings[cstr] == null)
                {
                    return new SqlConnection(cstr);
                }
                else
                {
                    return new SqlConnection(ConfigurationManager.ConnectionStrings[cstr].ConnectionString);
                }
            }

            return new SqlConnection(ConfigurationManager.ConnectionStrings["QfDefaultConnection"].ConnectionString);
        }

Again, good work.  It really is a great solution to an ongoing pain.

Scott...

**Comment by bbsimonbb** [comment]
Hi, just to make sure I understand, you want to be able to use the connection string --QfDefaultConnection, specified in the SQL, as the runtime connection. I wrote this with the intention of specifying the design-time connection in the SQL, not the run-time connection. But why not. If we pass the command text as you suggest, folk can do what they want. Might be a nice idea.

**Comment by me-slove** [comment]
Yes, you understand.  The idea of the elegance of the design time lookups works perfectly well at runtime.

As I said, our use case is to build a regression test system which uses many server/database combinations.  This way our QA folks don't really have to understand how to use the tool except the basics to write some SQL and it works brilliantly for them to hook it into NUnit.

Here's an example:

        [Test]
        public void CountTransactionHeader()
        {
            var ctr = new Counter();
            var ctr2 = new Counter2();
            Assert.AreEqual(ctr2.GetOne(DateTime.Parse("10/30/2016"), DateTime.Parse("10/31/2016")).TransactionCountBetween,
                ctr.GetOne(DateTime.Parse( "10/30/2016"),DateTime.Parse("10/31/2016")).TransactionCountBetween);
        }

**Comment by bbsimonbb** [comment]
Closing this for now. I think it's an edge case, but I'll have something for you in a forthcoming version. Fork and hack into the existing code if you want something in the meantime.
