### ISSUE TITLE
Ability to regenerate wrappers for selected sql file(s), not all of them

### ISSUE THREAD

**Issue by TomaszP1987** [bbsimonbb/query-first#84]
I got to maintain, improve and extend project which has FEW HUNDRED of sql queries and their query-first wrappers.
When I need to update or generate code for just 1 query, currently all of them all processed unnecessarily - small time lose,
but there is also some more serious problem:

Some partial classes of query results implement interfaces defined in external project and imported to this one
and result class type is replaced in generated code with (first of) implemented interfaces (with coma)
while it's using namespace statement is not added there and there are errors about unknown types,
so after each regeneration there are multiple files which require manual fixing - pasting using of interface's namespace.

I would really appreciate if it would be possible to generate code only for for selected sql file(s).

**Comment by bbsimonbb** [comment]
Well for your first issue, just saving an individual file will regenerate its wrapper. Get that working first then we can have a look a the other things. Have you found the QueryFirst tab in the ouput pane ? This will tell you what's going on.

**Comment by TomaszP1987** [comment]
Thanks, I checked what happens, solved the problem and that part works.

When some other project in the solution was unloaded (which should be checked before processing it):

Object reference not set to an instance of an object:
in QueryFirst.CheckPrerequisites.checkInFolder(ProjectItems items, Boolean& foundConfig, Boolean& foundQfRuntimeConnection)
in  C:\dev\query-first\Shared\CheckPrerequisites.cs: row 114
in QueryFirst.CheckPrerequisites.<HasPrerequitesAsync>d__1.MoveNext()
in C:\dev\query-first\Shared\CheckPrerequisites.cs: row 24
in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
in QueryFirst.SolutionEventHandlers.<myDocumentEvents_DocumentSavedAsync>d__16.MoveNext()
in C:\dev\query-first\Shared\SolutionEventHandlers.cs: row 241
