### ISSUE TITLE
Breaking change: fields instead of properties

### ISSUE THREAD

**Issue by Quacil** [bbsimonbb/query-first#9]
Hi,
In the latest update (the one for VS2017), you have changed POCOs properties to fields.
That's a breaking change for me since I cannot inherit from my interfaces now.
Is there a particular reason for it?

PS: Your extension is awesome 👍

**Comment by bbsimonbb** [comment]
I think you must have skipped an update at some point. I changed this a while back. I'm very open to discussion on this. 

You want to be able to define a common interface for the POCOs of a number of queries, then have the POCOs inherit the interface? This is pretty fundamentally useful I'll concede. I changed them to fields for serialization. I even forget the details of this. I think Newtonsoft was dealing fine with the auto-implemented properties, but XML serializer was serializing the hidden backing field. Perhaps I need properties with a real backing field that I name myself. Is this the optimum solution?

I'll get straight onto it. Thanks for signalling. Bear in mind you're never trapped. If there's anything you don't like, override it.

**Comment by Quacil** [comment]
Yes this would be great. I use Newtonsoft for serializing so there was no problem for me.
Maybe I did skip an update.

And I know I'm not trapped since I can edit the *.gen.cs, but I'd rather not(I'm still fixing code of someone who did :) )

Thanks for fast reply.

**Comment by bbsimonbb** [comment]
Ok I've moved to read/write properties with an explicit backing field. Should have been like that from the start.

If you really really want to modify .gen.cs, perhaps delete the first line of the .sql, then QueryFirst will ignore the file and your changes won't  be overwritten. I was suggesting though to override the MakeProperty() method, so you can structure the POCO how you want, but still be in the system.

ps. What changes did your colleague need to make in his/her .gen.cs?

pps. Would you consider leaving a comment somewhere on geniusorfantasist.blogspot.fr, please !?

**Comment by Quacil** [comment]
Thanks, works like a charm 👍 

What my colegue used to do is:
1. Create a main file GetObject.sql to generate POCO
2. Create sql files for the rest of the queries (example GetObjectByDate.sql)
3. Put code for the rest of the queries in the GetObject.gen.cs (example ExecuteByDate())
4. Then exclude *.gen.cs (example GetObjectByDate.gen.cs) from project
And he did it to use one POCO across the code.

I'll write a comment no problem.

**Comment by bbsimonbb** [comment]
Ok well there's no anticipating folk's imagination ! He might be permanently afflicted by the repository pattern. Can you tell him from me... extract the interface of the first POCO, then inherit this interface on all your POCOs, then, in the consuming code, just refer to the interface. I imagine this is what you did when you say "corrected"? Of course this works now again thanks to your suggested change ! That way, your queries stay "live", and you get notified if ever a query result diverges from the interface it's meant to fulfill. All the magic is in keeping the wrapper code constantly fresh.

**Comment by Quacil** [comment]
Yes this is exactly what I do and what I meant. Thanks again.
